/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "playerbalancer-parent"
include(":playerbalancer-velocity")
include(":playerbalancer-addon")

project(":playerbalancer-velocity").projectDir = file("balancer-velocity")
project(":playerbalancer-addon").projectDir = file("addon")
