name: PlayerBalancerAddon
main: com.jaimemartz.playerbalanceraddon.PlayerBalancerAddon
version: $version
authors: [jaime29010, BGHDDevelopment]
softdepend: [PlaceholderAPI]

commands:
  spb:
    description: Command to interact with the bungee side of PlayerBalancer
    permission: playerbalancer.admin