/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.github.goooler.shadow") version "8.1.7"
}

dependencies {
    api(libs.org.spongepowered.configurate.hocon)
    api(libs.org.bstats.bstats.velocity)
    compileOnly("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")
    annotationProcessor("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")
    compileOnly(libs.com.google.guava.guava)
    compileOnly(libs.com.google.inject.guice)
    compileOnly(libs.com.imaginarycode.minecraft.redisbungee)
}

description = "PlayerBalancer Velocity"
