/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.spongepowered.configurate.hocon)
    api(libs.org.bstats.bstats.velocity)
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.com.google.guava.guava)
    compileOnly(libs.com.google.inject.guice)
    compileOnly(libs.com.imaginarycode.minecraft.redisbungee)
}

description = "PlayerBalancer Velocity"
